hostname: identity.yas.local.com
backofficeRedirectUrl: http://backoffice.yas.local.com
storefrontRedirectUrl: http://storefront.yas.local.com
postgresql:
  host: postgres.yas-dev.svc.cluster.local
  port: 5432
  database: keycloak
  username: admin
  password: admin

bootstrapAdmin:
  username: admin
  password: admin