hostname: identity.yas.local.com

backofficeRedirectUrls:
  prod: http://backoffice.yas.local.com
  dev: http://backoffice.dev.local.com
  staging: http://backoffice.staging.local.com

storefrontRedirectUrls:
  prod: http://storefront.yas.local.com
  dev: http://storefront.dev.local.com
  staging: http://storefront.staging.local.com

postgresql:
  username: yasadminuser
  password: admin

bootstrapAdmin:
  username: admin
  password: admin