apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata: { name: cart, namespace: yas-dev, labels: { app: cart, env: dev } }
    spec:
      replicas: 1
      selector: { matchLabels: { app: cart } }
      template:
        metadata: { labels: { app: cart, env: dev } }
        spec:
          containers:
            - name: cart
              image: khanhnv2281/yas:cart-latest
              ports: [{ containerPort: 8084 }]
  - apiVersion: v1
    kind: Service
    metadata: { name: cart, namespace: yas-dev, labels: { app: cart, env: dev } }
    spec:
      selector: { app: cart }
      ports: [{ name: http, port: 80, targetPort: 8084 }]
