apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata: { name: inventory, namespace: yas-dev, labels: { app: inventory, env: dev } }
    spec:
      replicas: 1
      selector: { matchLabels: { app: inventory } }
      template:
        metadata: { labels: { app: inventory, env: dev } }
        spec:
          containers:
            - name: inventory
              image: khanhnv2281/yas:inventory-latest
              ports: [{ containerPort: 8090 }]
  - apiVersion: v1
    kind: Service
    metadata: { name: inventory, namespace: yas-dev, labels: { app: inventory, env: dev } }
    spec:
      selector: { app: inventory }
      ports: [{ name: http, port: 80, targetPort: 8090 }]
