apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata: { name: order, namespace: yas-dev, labels: { app: order, env: dev } }
    spec:
      replicas: 1
      selector: { matchLabels: { app: order } }
      template:
        metadata: { labels: { app: order, env: dev } }
        spec:
          containers:
            - name: order
              image: khanhnv2281/yas:order-latest
              ports: [{ containerPort: 8085 }]
  - apiVersion: v1
    kind: Service
    metadata: { name: order, namespace: yas-dev, labels: { app: order, env: dev } }
    spec:
      selector: { app: order }
      ports: [{ name: http, port: 80, targetPort: 8085 }]
