apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata: { name: customer, namespace: yas-staging, labels: { app: customer, env: staging } }
    spec:
      replicas: 1
      selector: { matchLabels: { app: customer } }
      template:
        metadata: { labels: { app: customer, env: staging } }
        spec:
          containers:
            - name: customer
              image: khanhnv2281/yas:customer-latest
              ports: [{ containerPort: 8088 }]
  - apiVersion: v1
    kind: Service
    metadata: { name: customer, namespace: yas-staging, labels: { app: customer, env: staging } }
    spec:
      selector: { app: customer }
      ports: [{ name: http, port: 80, targetPort: 8088 }]
