apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: yas-staging
resources:
  - backoffice.yaml
  - backoffice-bff.yaml
  - cart.yaml
  - customer.yaml
  - inventory.yaml
  - location.yaml
  - media.yaml
  - order.yaml
  - payment.yaml
  - payment-paypal.yaml
  - product.yaml
  - promotion.yaml
  - rating.yaml
  - recommendation.yaml
  - sampledata.yaml
  - search.yaml
  - storefront.yaml
  - storefront-bff.yaml
  - tax.yaml
  - webhook.yaml
