apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata: { name: payment-paypal, namespace: yas-staging, labels: { app: payment-paypal, env: staging } }
    spec:
      replicas: 1
      selector: { matchLabels: { app: payment-paypal } }
      template:
        metadata: { labels: { app: payment-paypal, env: staging } }
        spec:
          containers:
            - name: payment-paypal
              image: khanhnv2281/yas:payment-paypal-latest
              ports: [{ containerPort: 8093 }]
  - apiVersion: v1
    kind: Service
    metadata: { name: payment-paypal, namespace: yas-staging, labels: { app: payment-paypal, env: staging } }
    spec:
      selector: { app: payment-paypal }
      ports: [{ name: http, port: 80, targetPort: 8093 }]
