apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata: { name: sampledata, namespace: yas-staging, labels: { app: sampledata, env: staging } }
    spec:
      replicas: 1
      selector: { matchLabels: { app: sampledata } }
      template:
        metadata: { labels: { app: sampledata, env: staging } }
        spec:
          containers:
            - name: sampledata
              image: khanhnv2281/yas:sampledata-latest
              ports: [{ containerPort: 8094 }]
  - apiVersion: v1
    kind: Service
    metadata: { name: sampledata, namespace: yas-staging, labels: { app: sampledata, env: staging } }
    spec:
      selector: { app: sampledata }
      ports: [{ name: http, port: 80, targetPort: 8094 }]
